# config.yaml
# Database configuration
radar_resolution: 0.040308
cart_resolution: 0.2384
min_r: 2.0
max_r: 69.0
radar_data:
# Database connection string
  grassy:
    rosbag_path: 
      teach: "/home/samqiao/ASRL/vtr3_testing/localization_data/rosbags/grassy2"
      repeat1: "/home/samqiao/ASRL/vtr3_testing/localization_data/rosbags/grassy3"
    pose_graph_path: 
      grassy_t2_r3: "/home/samqiao/ASRL/vtr3_testing/localization_data/posegraphes/grassy_t2_r3/graph"

ppk:
  teach: "/home/samqiao/ASRL/vtr3_testing/localization_data/ppk/grassy_t2"
  repeat: "/home/samqiao/ASRL/vtr3_testing/localization_data/ppk/grassy_t3"


bool:
  SAVE: False
  PLOT: False
  DEBUG: True

output: "/home/samqiao/ASRL/vtr3_testing/scripts/direct"

