# config.yaml
# Database configuration
parent_folder: "/home/samqiao/ASRL/vtr3_testing"
radar_resolution: 0.040308
cart_resolution: 0.2384
min_r: 2.0
max_r: 69.0
radar_data:
# Database connection string
  grassy:
    rosbag_path: 
      teach: "/home/samqiao/ASRL/vtr3_testing/localization_data/rosbags/grassy2"
      repeat1: "/home/samqiao/ASRL/vtr3_testing/localization_data/rosbags/grassy3"
    pose_graph_path: 
      grassy_t2_r3: "/home/samqiao/ASRL/vtr3_testing/localization_data/posegraphes/grassy_t2_r3/graph"
    teach_local_maps_path: "/home/samqiao/ASRL/vtr3_testing/scripts/direct/grassy_t2_r3/local_map_vtr"
    repeat_local_maps_path: none

  parking:
    pose_graph_path:
      parking_t3_r4: "/home/samqiao/ASRL/vtr3_testing/localization_data/posegraphes/parking_t3_r4/graph"
    teach_local_maps_path: "/home/samqiao/ASRL/vtr3_testing/scripts/direct/parking_t3_r4/local_map_vtr"

ppk:
  grassy:
    teach: "/home/samqiao/ASRL/vtr3_testing/localization_data/ppk/grassy_t2"
    repeat: "/home/samqiao/ASRL/vtr3_testing/localization_data/ppk/grassy_t3"
  parking:
    teach: "/home/samqiao/ASRL/vtr3_testing/localization_data/ppk/parking_t3"
    repeat: "/home/samqiao/ASRL/vtr3_testing/localization_data/ppk/parking_t4"

bool:
  SAVE: False
  PLOT: False
  DEBUG: True
  USE_LOCAL_MAP: True
  SET_INITIAL_GUESS: True

output: "/home/samqiao/ASRL/vtr3_testing/scripts/direct"